### ISSUE TITLE
Swap/Move players between teams possible?

### ISSUE THREAD

**Issue by quantuumsnot** [dota2unofficial/12v12#23] opened 2019-02-11 22:30 UTC
In some WC3 mods there was possible to swap or move players between teams when the following conditions are met:

1. Host or game master changed player teams due to ingame request or imbalances in forces
2. Two or more players left from one of the teams and manually/automatically one or more from the stronger team are moved to the weaker team

If this is possible it will be very good for the game balance (playing with -2 whole game never been ok)

**Comment by win98se** [comment] 2019-02-18 16:46
You can refer to #7.

**Comment by darklordabc** [comment] 2019-09-10 05:03
Duplicate of #7

**Closed** 2019-09-10 05:04 UTC
