### ISSUE TITLE
Reset MMR patron feature

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#195] opened 2021-01-26 07:28 UTC
High tier patrons can reset when ever they want.
Normal patrons can reset every two weeks.
Consumable items in shop.

**Comment by SanctusAnimus** [comment] 2021-01-26 10:20
Duplicate of #176 ?

**Comment by SanctusAnimus** [comment] 2021-01-27 12:10
![](https://github.trello.services/images/mini-trello-icon.png) [MMR reset in 12v12/OT](https://trello.com/c/UsMgHYyh/2-mmr-reset-in-12v12-ot)

**Comment by darklordabc** [comment] 2021-01-29 13:54
![](https://github.trello.services/images/mini-trello-icon.png) [Implement MMR Reset](https://trello.com/c/zcdvrnpO/189-implement-mmr-reset)

**Comment by darklordabc** [comment] 2021-01-29 13:54
![](https://github.trello.services/images/mini-trello-icon.png) [Implement MMR Reset](https://trello.com/c/rQ6wSo5b/188-implement-mmr-reset-sheo)

**Comment by fcalife** [comment] 2021-01-30 04:12
Addendum: manually resetting your MMR does not grant any season reset rewards.

When resetting your MMR, your new MMR will be considered when the season resets. Your old MMR is permanently lost.

This should be a clear warning on the item's tooltip.

**Comment by SanctusAnimus** [comment] 2021-01-30 14:36
1) Should it reset MMR for custom game it was used in or for entire account?
2) If reset applies to custom games separately, should it have separate cooldowns for each too?
3) Interval for high supporters is indeed 2 weeks? Previous revisions of this issue were saying 30 days, just to be sure

**Comment by darklordabc** [comment] 2021-01-31 02:54
1 and 2. This feature should just be for 12v12, not overthrow. It should not effect Overthrow MMR.
3. Interval for NORMAL supporters is 2 weeks, high supporters can use it whenever they want, no cool down.

**Comment by Sheodar** [comment] 2021-02-01 11:25
Added

**Closed by Sheodar** 2021-02-01 11:25 UTC
